#!/usr/bin/env python3

from datetime import datetime

def gen_index(content):
    with open ("index.html", "w") as o:
        o.write(content)

content = "<!doctype html><html lang=es><meta charset=utf-8>"

content += "<title>Reticulado</title>"
content += str(datetime.now())

gen_index(content)
