#!/usr/bin/env python3

from datetime import datetime
from pan import d


def gen_index(content):
    with open ("index.html", "w") as o:
        o.write(content)

content = "<!doctype html><html lang=es><meta charset=utf-8>"

content += "<title>Reticulado</title>"

content += '<table><caption>Ingredientes'
for i, q in d['ingredientes']:
    content += '<tr><td>' + i + '<td>' + str(100*q)

content += '</table>'
content += '<p>' + str(datetime.now())
gen_index(content)
